# Uncomment the next line to define a global platform for your project
  platform :ios, '12.0'

target 'YelpReviewApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YelpReviewApp
  pod 'Alamofire'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Kingfisher', '~> 7.0'

  target 'YelpReviewAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YelpReviewAppUITests' do
    # Pods for testing
  end

end
